/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void convertFromJson() throws FileNotFoundException {
        FileReader fileReader = new FileReader("src/main/java/recentquotes.json");
        Gson gson = new Gson();
        List<Map> list =gson.fromJson(fileReader , List.class);
        Quotes quotes = new Quotes(list.get(6));

        assertEquals("Contants:{author: 'Louis Armstrong', text: What we play is life.\"}" , quotes.toString() );
    }

    @Test public void convertFromJson2() throws FileNotFoundException {
        FileReader fileReader = new FileReader("src/main/java/recentquotes.json");
        Gson gson = new Gson();
        List<Map> list =gson.fromJson(fileReader , List.class);
        Quotes quotes = new Quotes(list.get(10));

        assertEquals("Contants:{author: 'Chuck Klosterman', text: It's easier to believe there's a monster under the bed if you've spent the last six months arguing with a monster.\"}" , quotes.toString() );
    }

}
