/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {

        System.out.println(new App().getGreeting());

        FileReader fileReader = new FileReader("src/main/java/recentquotes.json");
        Gson gson = new Gson();

        List<Map> list =gson.fromJson(fileReader , List.class);

        int min=0;
        int max =list.size() -1 ;
        int j = (int) (Math.random()*(max-min+1)+min);

        Map randomItem = list.get(j);

        Quotes quotes = new Quotes(randomItem);



        }
    }

